
   
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JToolBar;
import menu.MenuItem;

/**
 *
 * @author RavenPC
 */
public class GenSettingsButtonPanel extends javax.swing.JPanel {
	
	private String uname = "root";
	private String pass = "Jo6c!pi7papaxen";
	private String query = "select* from generalsettings";
	private String url = "jdbc:mysql://localhost:3306/users";
	private String s = "";
	
    /**
     * Creates new form Panel1
     */
    public GenSettingsButtonPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	try {
    		Class.forName("com.mysql.cj.jdbc.Driver");
    	}
    	catch(ClassNotFoundException e) {
    		e.printStackTrace();    		
    	}
    	
    	try {
    		Connection con =  DriverManager.getConnection(url,uname,pass);
    		Statement statement = con.createStatement();
    		ResultSet result = statement.executeQuery(query);
    		
    		while(result.next()) {
    			
    			for(int i=1;i<4;i++) {
    				s+= result.getString(i).toString() + ":";
    			}
    		}
    		String strings[] = s.split(":",5);
    		System.out.println(s);
    		
    		
    	
    	
    	//ImageIcon saveIcon = new ImageIcon(getClass().getResource("C:\\Users\\dai18\\eclipse-workspace\\Bonaros AE Admin\\Form Icons\\save.png"));
    	//ImageIcon exitIcon = new ImageIcon(getClass().getResource("C:\\Users\\dai18\\eclipse-workspace\\Bonaros AE Admin\\Form Icons\\exit.png"));
        jLabel1 = new javax.swing.JLabel();
        jname = new javax.swing.JLabel("¼íïìá : ");
        nameField = new javax.swing.JTextField();
        nameField.setEditable(true);
        jname.setMaximumSize(new Dimension(Short.MAX_VALUE,Short.MAX_VALUE));
        jname.setPreferredSize(new Dimension(100,20));
        //MenuItem saveButton = new MenuItem(saveIcon,"Save",null);
        //MenuItem exitButton = new MenuItem(exitIcon,"Exit",null);
        
        trueTare = new javax.swing.JRadioButton("true");
        falseTare = new javax.swing.JRadioButton("false");
        trueInstance = new javax.swing.JRadioButton("true");
        falseInstance = new javax.swing.JRadioButton("true");
        
       
        tare = new javax.swing.JLabel("Tare");
        
        instance = new javax.swing.JLabel("Instant Preview");
        
        nameField.setText(strings[0]);
        
        if(strings[1].equals("1")) {
        	trueTare.setSelected(true);
        }else {
        	falseTare.setSelected(true);
        }
        
        
        if(strings[2].equals("1")) {
        	trueInstance.setSelected(true);
        }else {
        	falseInstance.setSelected(true);
        }
        
        
        Box tareBox = Box.createHorizontalBox();
        
        tareBox.setBackground(Color.BLACK);
        tareBox.add(Box.createRigidArea(new Dimension(80,80)));
        tareBox.add(tare);
        tareBox.add(Box.createRigidArea(new Dimension(120,120)));
        tareBox.add(trueTare);
        tareBox.add(Box.createRigidArea(new Dimension(20,20)));
        tareBox.add(falseTare);
        
        Box instBox = Box.createHorizontalBox();
        
        instBox.setBackground(Color.BLACK);
        instBox.add(Box.createRigidArea(new Dimension(80,80)));
        instBox.add(instance);
        instBox.add(Box.createRigidArea(new Dimension(66,66)));
        instBox.add(trueInstance);
        instBox.add(Box.createRigidArea(new Dimension(20,20)));
        instBox.add(falseInstance);
        
        Box nameBox = Box.createHorizontalBox();
        
        nameBox.add(Box.createRigidArea(new Dimension(80,80)));
        nameBox.add(jname);
        nameBox.add(Box.createRigidArea(new Dimension(120,120)));
        nameBox.add(nameField);
        
       
        
        saveButton = new javax.swing.JButton();
        saveButton.setText("ÁÐÏÈÇÊÅÕÓÇ");
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setEditable(true);
        jLabel1.setBackground(new java.awt.Color(155, 156, 237));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("    ÃåíéêÝò Ñõèìßóåéò");
        jLabel1.setOpaque(true);
        Box buttonBox = Box.createHorizontalBox();
        buttonBox.add(Box.createRigidArea(new Dimension(30,30)));
        buttonBox.add(saveButton);
        

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        
       
        
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)            
            .addGroup(layout.createParallelGroup()
                .addGap(10, 10, 10)
                .addComponent(buttonBox)
                .addGap(10, 10, 10)
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING))
            	.addGap(10, 10, 10)
            	.addComponent(nameBox,0,530,javax.swing.GroupLayout.PREFERRED_SIZE)
            	.addGap(10, 10, 10)
            	.addComponent(tareBox)
            	.addGap(10, 10, 10)
            	.addComponent(instBox)
                //.addContainerGap(220, Short.MAX_VALUE))
        ));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(buttonBox,0,30,javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60,60,60)                
                .addGroup(layout.createSequentialGroup())
                .addComponent(nameBox,0,30,javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tareBox)                
            	.addComponent(instBox)
                )
        ));
        
        
        
        
        trueTare.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				
				falseTare.setSelected(false);
				
				
			}
        	
        });
        
        falseTare.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				trueTare.setSelected(false);
				
			}
        	
        });
        
        trueInstance.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				falseInstance.setSelected(false);
				
			}
        	
        });
        
        falseInstance.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				trueInstance.setSelected(false);
				
			}
        	
        });
        
        
        saveButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				
				String deleteQuery = "delete from generalsettings";
				  try {
				  statement.executeUpdate(deleteQuery);
				  } catch (SQLException e1) {
					  e1.printStackTrace();
				  }
				
				
				boolean tare;
				boolean instance;
				String name = nameField.getText();
				System.out.println(name);
				
				if(trueTare.isSelected()) {
					tare = true;
				} else {
					tare = false;
				}
				
				if(trueInstance.isSelected()) {
					instance=true;
				} else {
					instance = false;
				}
				
				
				
				try {
					String q = "INSERT INTO generalsettings(GeneralName,Tare,Instance) VALUES ('"+name+"',"+tare+","+instance+")";
					statement.executeUpdate(q);
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				
				
			}
        	
        	});
    	}
        
        catch(SQLException e) {
    		e.printStackTrace();
    	}
    	
        
        	
        
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jname;
    private javax.swing.JTextField nameField;
    private javax.swing.JRadioButton trueTare;
    private javax.swing.JRadioButton falseTare;
    private javax.swing.JRadioButton trueInstance;
    private javax.swing.JRadioButton falseInstance;
    private javax.swing.JLabel tare;
    private javax.swing.JLabel instance;
    // End of variables declaration//GEN-END:variables
}
