package form;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Vector;

import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.WindowConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;

import com.github.lgooddatepicker.tableeditors.DateTableEditor;
import com.toedter.calendar.JDateChooser;



	public class ProductPanel extends javax.swing.JPanel {
		
		
		private String uname = "root";
		private String pass = "Jo6c!pi7papaxen";
		private String query = "select* from products";
		private String url = "jdbc:mysql://localhost:3306/users?useTimezone=true&serverTimezone=UTC";
		private int id = 0;
		private static JTable table;
		private TableRowSorter sorter = new TableRowSorter();
		private static int selectedColumn = 0;
	
		
		 public void removeSelectedFromTable(JTable table) {

		        DefaultTableModel model = (DefaultTableModel) table.getModel();
		        int indexes[] = table.getSelectedRows(); 
		        int res = 0;
		        for(int i = 0; i < indexes.length; i++) {
		            res += (i>0)?(indexes[i]-indexes[i-1]-1):0;
		            int index = table.convertRowIndexToModel(indexes[0]+res);
		            model.removeRow(index);
		        }
		    }
		 
		 

	    /**
	     * Creates new form Panel1
	     */
	    public ProductPanel() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {
	    	   	
	    	try {
	    		Class.forName("com.mysql.cj.jdbc.Driver");
	    	}
	    	catch(ClassNotFoundException e) {
	    		e.printStackTrace();    		
	    	}
	    	
	    	try {
	    		Connection con =  DriverManager.getConnection(url,uname,pass);
	    		Statement statement = con.createStatement();
	    		ResultSet result = statement.executeQuery(query);
	    		ResultSetMetaData rsmt = result.getMetaData();
	    		
	    		int c = rsmt.getColumnCount();
	    		Vector column = new Vector(c);
	    		for(int i=1;i<=c;i++) {
	    			
	    			column.add(rsmt.getColumnName(i));
	    		}
	    		Vector data = new Vector();
	    		Vector row = new Vector();
	    		
	    		while(result.next()) {
	    			row = new Vector(c);
	    			for(int i=1;i<=c;i++) {
	    				row.add(result.getString(i));
	    				
	    			}
	    			data.add(row);
	    		}
	    		
	    		
	    		DefaultTableModel model = new DefaultTableModel(data,column) {

	    		    @Override
	    		    public boolean isCellEditable(int row, int column) {
	    		    	
	    		    		return false;
	    		    }
	    		};
	    		
	    		
	    		 
	    		
	    		
	    		
	    		sorter.setModel(model);
	    	    table = new javax.swing.JTable(model);
	        	table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
	        	table.setRowSorter(sorter);
	        	table.setRowHeight(30);
	        	
	        	JComboBox<String> jComboBox = new JComboBox<>(column);
	        	jComboBox.addActionListener(new ActionListener() {

					@Override
					public void actionPerformed(ActionEvent e) {
						selectedColumn = jComboBox.getSelectedIndex();
						
					}
	        		
	        	});
	        	
	        	JTextField searchField = new JTextField();
	        	searchField.setPreferredSize(new Dimension(60,30));
	        	JLabel searchlabel = new JLabel("Αναζήτηση:");
	        	searchlabel.setFont(new Font("Arial",Font.BOLD,12));
	        	Box searchBox = Box.createHorizontalBox();
	        	selectedColumn = jComboBox.getSelectedIndex();
	        	searchField.getDocument().addDocumentListener(new DocumentListener() {
	        		
	        		
	                @Override
	                public void insertUpdate(DocumentEvent e) {
	                   search(searchField.getText());
	                }
	                @Override
	                public void removeUpdate(DocumentEvent e) {
	                   search(searchField.getText());
	                }
	                @Override
	                public void changedUpdate(DocumentEvent e) {
	                   search(searchField.getText());
	                }
	                public void search(String str) {
	                   if (str.length() == 0) {
	                      sorter.setRowFilter(null);
	                   } else {
	                	  
	                      sorter.setRowFilter(RowFilter.regexFilter(str,selectedColumn));
	                   }
	                }
	             });
	        	searchBox.add(searchlabel);
	        	searchBox.add(Box.createRigidArea(new Dimension(10,0)));
	        	searchBox.add(searchField);
	        	searchBox.add(Box.createRigidArea(new Dimension(10,0)));
	        	searchBox.add(jComboBox);
	        	searchBox.setPreferredSize(new Dimension(80,30));
	        	searchBox.setMaximumSize(new Dimension(Short.MAX_VALUE,Short.MAX_VALUE));
	        	//JScrollPane Settings
	        	
	        	pane = new javax.swing.JScrollPane(table);
	        	//Horizontal Policy
	        	int horizontalPolicy = JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS;
	        	//Vertical Policy
	        	int vericalPolicy = JScrollPane.VERTICAL_SCROLLBAR_ALWAYS;
	        	pane.setHorizontalScrollBarPolicy(horizontalPolicy);
	        	pane.setVerticalScrollBarPolicy(vericalPolicy);
	        	
	        	
	        	
	        	pane.setPreferredSize(new Dimension(150,10));
	        	
	            jLabel1 = new javax.swing.JLabel();
	            
	            save = new javax.swing.JButton();
	            save.setText("ΑΠΟΘΗΚΕΥΣΗ");
	            deleteButton = new javax.swing.JButton();
	            deleteButton.setText("ΔΙΑΓΡΑΦΗ");
	            insert = new javax.swing.JButton();
	            insert.setText("ΕΙΣΑΓΩΓΗ");
	                   
	            jTextField1 = new javax.swing.JTextField();

	            jLabel1.setBackground(new java.awt.Color(155, 156, 237));
	            jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
	            jLabel1.setText("    ΠΡΟΙΟΝΤΑ");
	            jLabel1.setOpaque(true);
	            
	            Box buttonBox = Box.createHorizontalBox();
	            buttonBox.add(Box.createRigidArea(new Dimension(20,20)));
	            buttonBox.add(save);
	            buttonBox.add(Box.createRigidArea(new Dimension(20,20)));
	            buttonBox.add(insert);
	            buttonBox.add(Box.createRigidArea(new Dimension(20,20)));
	            buttonBox.add(deleteButton);
	            
	          
	            
	            
	            jTextField1.addActionListener(new java.awt.event.ActionListener() {
	                public void actionPerformed(java.awt.event.ActionEvent evt) {
	                    jTextField1ActionPerformed(evt);
	                }
	            });
	            
	            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	            
	          
	            
	            this.setLayout(layout);
	            
	            
	            layout.setHorizontalGroup(
	                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)                
	                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING))       
	                .addComponent(buttonBox)
	                .addGap(30,30,30)
	                .addComponent(searchBox,30,380,400)
	                .addComponent(pane,10,600,1000));
	                                
	            layout.setVerticalGroup(
	                layout.createSequentialGroup()  
	                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addGroup(layout.createSequentialGroup()
	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE))
	                    .addComponent(buttonBox)
	                    .addGap(30,30,30)
	                    .addComponent(searchBox,30,30,30)
	                    .addGap(30,30,30)
	                    .addComponent(pane,10,200,750)));                 
	                    
	            
	            
	            table.addMouseListener(new MouseAdapter() {
	            	public void mouseClicked(MouseEvent e) {
	            		int row = table.getSelectedRow();
	            		if(e.getClickCount()==2) {
	            			
	            			
	            			new ProductEditPanel(table,row);
	            			
	            			
	            		}
	            	}
	            });
	            
	            
	                    
	            		
	            
	            	save.addActionListener(new ActionListener() {
	    			
	    			@Override
	    			public void actionPerformed(ActionEvent e) {
							
							  String deleteQuery = "delete from products";
							  try {
							  statement.executeUpdate(deleteQuery);
							  } catch (SQLException e1) {
								  e1.printStackTrace();
							  }
							  
								 
							 
							 
	    				for(int i=0;i<table.getRowCount();i++) {
	    					
	    				String id = table.getValueAt(i, 0).toString();
	    				String barcode = table.getValueAt(i,1).toString();
	    				String description = table.getValueAt(i, 2).toString();
	    				String price =  table.getValueAt(i,3).toString();
	    				String daysToexpire = table.getValueAt(i,4).toString();
	    				String dateProduct = table.getValueAt(i, 5).toString();
	    				String lot = table.getValueAt(i, 6).toString();
	    				String serialNumber = table.getValueAt(i, 7).toString();
	    				String tarePercentage = table.getValueAt(i, 8).toString();
	    				String smallItemWeight = table.getValueAt(i, 9).toString();
	    				String piecesperbox = table.getValueAt(i, 10).toString();
	    				String piecesperpallete = table.getValueAt(i, 11).toString();
	    				String labelPiece =  table.getValueAt(i, 12).toString();
	    				String labelBox = table.getValueAt(i, 13).toString();
	    				String labelPallete = table.getValueAt(i, 14).toString();
	    				String underWeight = table.getValueAt(i, 15).toString();
	    				String overWeight = table.getValueAt(i, 16).toString();
	    				String expireDate = table.getValueAt(i, 18).toString();
	    				String packingDate = table.getValueAt(i, 19).toString();
	    			
	    				try {
							int pId = Integer.parseInt(id);		
	    					int ppb = Integer.parseInt(piecesperbox);
	    					int ppp = Integer.parseInt(piecesperpallete);
							String query1 = "insert into products(idProducts,barcode,description,price,daystoexpire,dateproduct,lot,serialnumber,tarePercentage,smallItemWeight,piecesperbox,boxesperpallete,labelpiece,labelbox,labelpallete,underWeight,overWeight,textsId,expireDate,packingDate) values("+pId+",'"+barcode+"','"+description+"','"+price+"','"+daysToexpire+"','"+dateProduct+"','"+lot+"','"+serialNumber+"','"+tarePercentage+"','"+smallItemWeight+"',"+ppb+","+ppp+",'"+labelPiece+"','"+labelBox+"','"+labelPallete+"','"+underWeight+"','"+overWeight+"',"+pId+",'"+packingDate+"','"+expireDate+"')";
							statement.executeUpdate(query1);
							
						} catch (SQLException e2) {
							// TODO Auto-generated catch block
							e2.printStackTrace();
						}
	    				
	    				
	    				
	    				
	    				}
	    				
	    				new SuccessSaveGUI();
	    				
	    			}
	    		});
	            	deleteButton.addActionListener(new ActionListener() {

	    				@Override
	    				public void actionPerformed(ActionEvent e) {
	    				
	    					if(table.getSelectedRows().length==0) {
	    						NoRowProductGUI gui = new NoRowProductGUI();   						
	    						
	    					}
	    					
	    					else {
	    						
	    						JFrame powerFrame=  new JFrame("Διαγραφή Προϊόντος");
	    						JPanel panel = new JPanel();
	    						JLabel message = new JLabel("Είστε βέβαιος για την μόνιμη διαγραφή του προϊόντος; ");
	    						
	    						JButton yesButton = new JButton("ΝΑΙ");
	    						JButton noButton = new JButton("OXI");
	    						yesButton.setPreferredSize(new Dimension(100,10));
	    						yesButton.setMaximumSize(new Dimension(Short.MAX_VALUE,Short.MAX_VALUE));
	    						noButton.setPreferredSize(new Dimension(100,10));
	    						noButton.setMaximumSize(new Dimension(Short.MAX_VALUE,Short.MAX_VALUE));
	    						//�������� ��������
	    						yesButton.setAlignmentX(Component.CENTER_ALIGNMENT);
	    						noButton.setAlignmentX(Component.CENTER_ALIGNMENT);
	    						
	    						
	    						//�������� ��������
	    						message.setAlignmentX(Component.CENTER_ALIGNMENT);
	    						
	    						Box box = Box.createHorizontalBox();
	    						box.add(yesButton);
	    						box.add(Box.createRigidArea(new Dimension(20,20)));
	    						box.add(noButton);
	    						
	    						
	    						Box labelbox = Box.createVerticalBox();
	    						
	    						
	    						labelbox.add(Box.createRigidArea(new Dimension(200,20)));
	    						labelbox.add(message);
	    						
	    						yesButton.addActionListener(new ActionListener() {

	    							@Override
	    							public void actionPerformed(ActionEvent e) {
	    								
	    								
	    								removeSelectedFromTable(table);
	    								powerFrame.dispose();
	    								
	    							}
	    							
	    							
	    						});
	    						
	    						
	    						noButton.addActionListener(new ActionListener() {

	    							@Override
	    							public void actionPerformed(ActionEvent e) {
	    								powerFrame.dispose();
	    								
	    							}
	    							
	    						});
	    						
	    						
	    						panel.add(labelbox);
	    						panel.add(box);
	    						panel.setPreferredSize(new Dimension(400,100));
	    						
	    						
	    						powerFrame.add(panel);
	    						
	    						powerFrame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
	    				        powerFrame.pack();
	    				        powerFrame.setLocationRelativeTo(null);
	    				        powerFrame.setVisible(true);
	    				        powerFrame.setResizable(false);
	    					}
	    				 }
	    				});
	            	
	            	
	            	insert.addActionListener(new ActionListener() {
	            		
						@Override
						public void actionPerformed(ActionEvent e) {
							if(data.isEmpty()) {
								
								model.addRow(new Object[] {"","","",""});
								
							}
							else {
								
								model.addRow(new Object[] {"","","",""});
								id+=1;
							}
						}
						
						});
	            	}
						
	            		
	            
	    			
	    	
	    	catch(SQLException e) {
	    		e.printStackTrace();
	    	}
	    	
		
	        
	    }// </editor-fold>//GEN-END:initComponents

	    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
	        // TODO add your handling code here:
	    }
	    


	    // Variables declaration - do not modify//GEN-BEGIN:variables
	   
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JButton save;
	    private javax.swing.JTable users;
	    private javax.swing.JButton insert;
	    private javax.swing.JButton deleteButton;
	    private javax.swing.JScrollPane pane;
	    

	}
